### ISSUE TITLE
Missing File: /workspace/data/MulBench/cases.json in dataset.py

### ISSUE THREAD

**Issue by IemProg** [arctanxarc/MC-LLaVA#2]
Hi @arctanxarc @Hhankyangg ,

First of all, thank you for sharing such an interesting project and for making the code and dataset publicly available.

While setting up the training pipeline as described, I noticed that the file _/workspace/data/MulBench/cases.json_ is referenced in dataset.py but appears to be missing from the provided dataset or repository. 
Could you kindly provide this file or guide us on how to generate it?

Additionally, I wanted to ask if you have any timeline for sharing the complete codebase for the project. 

Looking forward to your response and thank you once again for this excellent contribution to the community!

Cheers,
Imad

**Comment by Hhankyangg** [comment]
Hi. Regarding your first point, the file /workspace/data/MulBench/cases.json mentioned in dataset.py actually corresponds to scenarios.json in our released dataset. We’ve already updated the repository to address this. Thank you for pointing this out!

As for the second question, the complete code and dataset have already been open-sourced. If you encounter any issues during reproduction or have further questions, feel free to reach out — I’ll be happy to help!

**Comment by IemProg** [comment]
Hi @Hhankyangg,

Thanks a lot for the clarification!

Regarding my second question, it concerns the training scripts mentioned as TODO in the README.md file. Specifically, I noticed there is no detailed information about the parameters and arguments used for training.

Could you kindly share any updates or clarify if these scripts and the associated configurations are planned to be released soon? It would greatly help to reproduce the results effectively.

Thank you again for your assistance!

**Comment by IemProg** [comment]
Also, the following files are missing from the "dataset.py" file:
```
        if pos_image:
            conversation_types.append('recognition_positive.json')
        if random_image:
            conversation_types.append('recognition_negative_cc12m.json')
        if conversation:
            conversation_types.append('conversation.json')
        if extreme_negative:
            conversation_types.append('recognition_strong_negative.json')
```

**Comment by Hhankyangg** [comment]
These files can be generated through templates, as shown in llava/build_qa.py. Additionally, I will update the docs in README as soon as possible this week.

**Comment by IemProg** [comment]
Hi @arctanxarc @Hhankyangg 

Thank you for the clarification regarding the file generation through `llava/build_qa.py`. I wanted to follow up and ask if there are any updates on the files or further instructions on how to generate them. 

It would also be really helpful if you could update the README with detailed steps to reproduce your results when possible.

Thanks in advance for your help!
